name = input("What is your name? ")
print(name)
sec = input("In which class do you study? ")
print(sec)
age = input("How old are you? ")
print(age)
subject = input("Which subject are you currently studying? ")
print(subject)
future = input("What do you want to do for living in future? ")
print(future)
time = input("What do like to do in your leisure time? ")
print(time)
person = input("What is your personality type? ")
print(person)
ratings = input("Out of 10 how much do you rate your self in real")
print(ratings)
words = input("If there are 5 words that best describe you, what are they?")
print(words)
maths = input("If p : It rains today, q : I go to school, r : I shall meet any friends and s : I shall go for a "
              "movie, then which of the following is the proposition ")
print(maths)

print("THANKS FOR COMPLETING THIS SHORT SURVEY I HOPE YOU FIND IT INTERESTING xD :)")
